### ISSUE TITLE
Exposed sensitive data

### ISSUE THREAD

**Issue by akankov** [BusyBee15/courier-hacks-open-source#1]
🚨 Exposed sensitive data. You should never do it.

But as you already [did](https://github.com/BusyBee15/courier-hacks-open-source/commit/a7c25fe674bbe3e4f00197a79b27fd74a8f23b6f) it, you at least hide it bu [squashing](https://www.git-tower.com/learn/git/faq/git-squash) commits

**Comment by BusyBee15** [comment]
@akankov  Thank you for raising this issue, I wouldn't have known otherwise.
